@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --onedir --windowed --icon "X:\cartelllla\git\sito\immagini\IO.ico" --name "Music_player" --add-data "X:\cartelllla\git\Music_Player\templates;templates/" --add-data "X:\cartelllla\git\Music_Player\static;static/" --add-data "X:\cartelllla\git\Music_Player\lib.py;." --add-data "X:\cartelllla\git\Music_Player\main.py;."  "X:\cartelllla\git\Music_Player\app.pyw"
rd /S /Q build
del Music_player.spec
pause
