services:
  music_player:
    image: dj2828/music_player:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    volumes:
      - /DATA/AppData/music_player:/app/data
      - ./import_docker:/app/music
    environment:
      - DOCKER=True
      - YT_FOLDER=/app/data/yt
      - MUSIC_FOLDER=/app/music
      - COVER_FOLDER=/app/data/cover
volumes:
  data: