services:
  music_player:
    image: dj2828/music_player:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - data:/app/data
      - ./import_docker:/app/music
    environment:
      - DOCKER=True
      - YT_FOLDER=/app/data/yt
      - MUSIC_FOLDER=/app/music
      - COVER_FOLDER=/app/data/cover
      - ALBUM_ORDER=23 6451, c@ra++ere spec!@le, sFaCioLaTe miXTaPe, CASA GOSPEL
volumes:
  data: